//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URLRedirect.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class urlredEntities : DbContext
    {
        public urlredEntities()
            : base("name=urlredEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<car> cars { get; set; }
        public DbSet<city> cities { get; set; }
        public DbSet<fruit> fruits { get; set; }
        public DbSet<redirect> redirects { get; set; }
    }
}
